apiVersion: v1
kind: ConfigMap
metadata:
  name: ae-usuarios-config
data:
  ae-apigateway-database-jdbc-url: 'jdbc:sqlserver://expensereportdemosqlserver.database.windows.net;databaseName=AE;encrypt=true;trustServerCertificate=true'
  ae-apigateway-url: 'https://ae:8080'
  ae-usuarios-database-jdbc-url: 'jdbc:sqlserver://expensereportdemosqlserver.database.windows.net;databaseName=AE;encrypt=true;trustServerCertificate=true'
  ae-usuarios-url: 'https://ae-usuarios:8081'
  ae-configuraciones-database-jdbc-url: 'jdbc:sqlserver://expensereportdemosqlserver.database.windows.net;databaseName=AE;encrypt=true;trustServerCertificate=true'
  ae-configuraciones-url: 'https://ae-configuraciones:8082'
  ae-reportes-database-jdbc-url: 'jdbc:sqlserver://expensereportdemosqlserver.database.windows.net;databaseName=AE;encrypt=true;trustServerCertificate=true'
  ae-reportes-url: 'https://ae-reportes:8083'
  ae-firmas-database-jdbc-url: 'jdbc:sqlserver://expensereportdemosqlserver.database.windows.net;databaseName=AE;encrypt=true;trustServerCertificate=true'
  ae-firmas-url: 'https://ae-firmas:8084'
  ae-personas-afiliados-contratantes-database-jdbc-url: 'jdbc:sqlserver://expensereportdemosqlserver.database.windows.net;databaseName=AE;encrypt=true;trustServerCertificate=true'
  ae-personas-afiliados-contratantes-url: 'https://ae-personas-afiliados-contratantes:8085'
  ae-solicitudes-database-jdbc-url: 'jdbc:sqlserver://expensereportdemosqlserver.database.windows.net;databaseName=AE;encrypt=true;trustServerCertificate=true'
  ae-solicitudes-url: 'https://ae-solicitudes:8086'
  ae-novedades-database-jdbc-url: 'jdbc:sqlserver://expensereportdemosqlserver.database.windows.net;databaseName=AE;encrypt=true;trustServerCertificate=true'
  ae-novedades-url: 'https://ae-novedades:8087'
  ae-generasolicitud-database-jdbc-url: 'jdbc:sqlserver://expensereportdemosqlserver.database.windows.net;databaseName=AE;encrypt=true;trustServerCertificate=true'
  ae-generasolicitud-url: 'https://ae-generasolicitud:8088'
---
apiVersion: v1
kind: Secret
metadata:
  name: ae-usuarios-secret
type: Opaque
data:
  db-password: SW50M2dyNG4wdjQ=
  db-username: SW50ZWdyYW5vdmE=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ae-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ae-usuarios
  template:
    metadata:
      labels:
        app: ae-usuarios
        app.kubernetes.io/component: ae-usuarios
        app.kubernetes.io/instance: ae-usuarios
        app.kubernetes.io/name: ae-usuarios
        app.kubernetes.io/part-of: ae-app
        app.openshift.io/runtime: ae-usuarios
    spec:
      containers:
        - name: ae-usuarios
          image: image-registry.openshift-image-registry.svc:5000/$(PROJECT_NAME)/ae-usuarios:latest
          ports:
            - containerPort: 8081
          env:
          - name: quarkus.datasource.jdbc.url
            valueFrom:
              configMapKeyRef:
                name: ae-usuarios-config
                key: ae-usuarios-database-jdbc-url
          - name: quarkus.datasource.username
            valueFrom:
              secretKeyRef:
                name: ae-usuarios-secret
                key: db-username
          - name: quarkus.datasource.password
            valueFrom:
              secretKeyRef:
                name: ae-usuarios-secret
                key: db-password
          - name: quarkus.rest-client.ae-apigateway.url
            valueFrom:
              configMapKeyRef:
                name: ae-usuarios-config
                key: ae-apigateway-url
          - name: quarkus.rest-client.ae-usuarios.url
            valueFrom:
              configMapKeyRef:
                name: ae-usuarios-config
                key: ae-usuarios-url
          - name: quarkus.rest-client.ae-configuraciones.url
            valueFrom:
              configMapKeyRef:
                name: ae-usuarios-config
                key: ae-configuraciones-url
          - name: quarkus.rest-client.ae-reportes.url
            valueFrom:
              configMapKeyRef:
                name: ae-usuarios-config
                key: ae-reportes-url
          - name: quarkus.rest-client.ae-firmas.url
            valueFrom:
              configMapKeyRef:
                name: ae-usuarios-config
                key: ae-firmas-url
          - name: quarkus.rest-client.ae-personas-afiliados-contratantes.url
            valueFrom:
              configMapKeyRef:
                name: ae-usuarios-config
                key: ae-personas-afiliados-contratantes-url
          - name: quarkus.rest-client.ae-solicitudes.url
            valueFrom:
              configMapKeyRef:
                name: ae-usuarios-config
                key: ae-solicitudes-url
          - name: quarkus.rest-client.ae-novedades.url
            valueFrom:
              configMapKeyRef:
                name: ae-usuarios-config
                key: ae-novedades-url
          - name: quarkus.rest-client.ae-generasolicitud.url
            valueFrom:
              configMapKeyRef:
                name: ae-usuarios-config
                key: ae-generasolicitud-url
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: ae-usuarios
  labels:
    app: ae-usuarios
    app.kubernetes.io/component: ae-usuarios
    app.kubernetes.io/instance: ae-usuarios
    app.kubernetes.io/name: ae-usuarios
    app.kubernetes.io/part-of: ae-app
    app.openshift.io/runtime: ae-usuarios
spec:
  selector:
    app: ae-usuarios
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ae-usuarios
spec:
  to:
    kind: Service
    name: ae-usuarios
  port:
    targetPort: '8081'
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ae-usuarios
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/jcarlosmolina/ae-usuarios.git'
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: ae-usuarios:latest
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ae-usuarios
