apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ae-usuarios
  labels:
    app: ae-usuarios
    app.kubernetes.io/component: ae-usuarios
    app.kubernetes.io/instance: ae-usuarios
    app.kubernetes.io/name: ae-usuarios
    app.kubernetes.io/part-of: ae-app
    app.openshift.io/runtime: ae-usuarios
spec:
  to:
    kind: Service
    name: ae-usuarios
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow