ALTER TABLE TM_ValorPregunta ADD CONSTRAINT pk_TM_ValorPregunta PRIMARY KEY (Identificador, Numero);
ALTER TABLE TM_DominioPeriodicidad ADD CONSTRAINT pk_TM_DominioPeriodicidad PRIMARY KEY (Numero, Codigo);
ALTER TABLE TM_DominioRol ADD CONSTRAINT pk_TM_DominioRol PRIMARY KEY (Numero, Identificador);
ALTER TABLE TM_DominioFormaPago ADD CONSTRAINT pk_TM_DominioFormaPago PRIMARY KEY (Numero, Codigo);
ALTER TABLE TM_DominiosPlantillas ADD CONSTRAINT pk_TM_DominiosPlantillas PRIMARY KEY (Numero, IdPlantilla);
ALTER TABLE TM_DominioNovedad ADD CONSTRAINT pk_TM_DominioNovedad PRIMARY KEY (Numero, id_Novedad);
ALTER TABLE TM_IncompatibilidadesDominio ADD CONSTRAINT pk_TM_IncompatibilidadesDomini PRIMARY KEY (Numero, DominiosIncompatibles_Numero);
ALTER TABLE TM_DirSucursalCTipoSucursalC ADD CONSTRAINT pk_TM_DirSucursalCTipoSucursal PRIMARY KEY (Codigo, TiposSucursalC_Codigo);
ALTER TABLE TM_AfiliacionesPlanes ADD CONSTRAINT pk_TM_AfiliacionesPlanes PRIMARY KEY (Id, Plan);
ALTER TABLE TM_AgentexProductoDominio ADD CONSTRAINT pk_TM_AgentexProductoDominio PRIMARY KEY (Id, AgentexProducto_Id, Numero);
ALTER TABLE TM_ReportesProcAlmFuncionario ADD CONSTRAINT pk_TM_ReportesProcAlmFuncionar PRIMARY KEY (id_Reporte, Id);
ALTER TABLE TM_GrupoAsignacionFuncionario ADD CONSTRAINT pk_TM_GrupoAsignacionFuncionar PRIMARY KEY (Id, Funcionario_Id);
ALTER TABLE Funcionario ADD CONSTRAINT pk_Funcionario PRIMARY KEY (Id);
ALTER TABLE Admin ADD CONSTRAINT pk_Admin PRIMARY KEY (Id);
ALTER TABLE SuperAdmin ADD CONSTRAINT pk_SuperAdmin PRIMARY KEY (Id);
ALTER TABLE Asesor ADD CONSTRAINT pk_Asesor PRIMARY KEY (Id);
ALTER TABLE AreaMedica ADD CONSTRAINT pk_AreaMedica PRIMARY KEY (Id);
ALTER TABLE Afiliaciones ADD CONSTRAINT pk_Afiliaciones PRIMARY KEY (Id);
ALTER TABLE RespRegional ADD CONSTRAINT pk_RespRegional PRIMARY KEY (Id);
ALTER TABLE Gestor ADD CONSTRAINT pk_Gestor PRIMARY KEY (Id);
ALTER TABLE MesaDeApoyo ADD CONSTRAINT pk_MesaDeApoyo PRIMARY KEY (Id);
ALTER TABLE ParamConfig ADD CONSTRAINT pk_ParamConfig PRIMARY KEY (Codigo);
ALTER TABLE LogParam ADD CONSTRAINT pk_LogParam PRIMARY KEY (Codigo);
ALTER TABLE FrecuenciaAct ADD CONSTRAINT pk_FrecuenciaAct PRIMARY KEY (Codigo);
ALTER TABLE CuestionarioMed ADD CONSTRAINT pk_CuestionarioMed PRIMARY KEY (Numero);
ALTER TABLE Seccion ADD CONSTRAINT pk_Seccion PRIMARY KEY (Identificador);
ALTER TABLE Pregunta ADD CONSTRAINT pk_Pregunta PRIMARY KEY (Numero);
ALTER TABLE Valor ADD CONSTRAINT pk_Valor PRIMARY KEY (Identificador);
ALTER TABLE Productos ADD CONSTRAINT pk_Productos PRIMARY KEY (Producto);
ALTER TABLE Planes ADD CONSTRAINT pk_Planes PRIMARY KEY (Plan);
ALTER TABLE Parentesco ADD CONSTRAINT pk_Parentesco PRIMARY KEY (Codigo);
ALTER TABLE Periodicidad ADD CONSTRAINT pk_Periodicidad PRIMARY KEY (Codigo);
ALTER TABLE Rol ADD CONSTRAINT pk_Rol PRIMARY KEY (Identificador);
ALTER TABLE Dominio ADD CONSTRAINT pk_Dominio PRIMARY KEY (Numero);
ALTER TABLE PlantillaEmail ADD CONSTRAINT pk_PlantillaEmail PRIMARY KEY (IdPlantilla);
ALTER TABLE EstadoContrato ADD CONSTRAINT pk_EstadoContrato PRIMARY KEY (Codigo);
ALTER TABLE EstadoBeneficiario ADD CONSTRAINT pk_EstadoBeneficiario PRIMARY KEY (Codigo);
ALTER TABLE EstadoBeneficiarioAE ADD CONSTRAINT pk_EstadoBeneficiarioAE PRIMARY KEY (Codigo);
ALTER TABLE Tarifa ADD CONSTRAINT pk_Tarifa PRIMARY KEY (Id);
ALTER TABLE Regional ADD CONSTRAINT pk_Regional PRIMARY KEY (Codigo);
ALTER TABLE Sucursal ADD CONSTRAINT pk_Sucursal PRIMARY KEY (Codigo);
ALTER TABLE GrupoAsociado ADD CONSTRAINT pk_GrupoAsociado PRIMARY KEY (Codigo);
ALTER TABLE EstadoCivil ADD CONSTRAINT pk_EstadoCivil PRIMARY KEY (Codigo);
ALTER TABLE Departamento ADD CONSTRAINT pk_Departamento PRIMARY KEY (Codigo);
ALTER TABLE TipoIVA ADD CONSTRAINT pk_TipoIVA PRIMARY KEY (Codigo);
ALTER TABLE Persona ADD CONSTRAINT pk_Persona PRIMARY KEY (Identificador);
ALTER TABLE Companyia ADD CONSTRAINT pk_Companyia PRIMARY KEY (Codigo);
ALTER TABLE Municipio ADD CONSTRAINT pk_Municipio PRIMARY KEY (Codigo);
ALTER TABLE TipoDireccion ADD CONSTRAINT pk_TipoDireccion PRIMARY KEY (Codigo);
ALTER TABLE EstadoPersona ADD CONSTRAINT pk_EstadoPersona PRIMARY KEY (Codigo);
ALTER TABLE FormaPago ADD CONSTRAINT pk_FormaPago PRIMARY KEY (Codigo);
ALTER TABLE TipoIdentificacion ADD CONSTRAINT pk_TipoIdentificacion PRIMARY KEY (Codigo);
ALTER TABLE EPS ADD CONSTRAINT pk_EPS PRIMARY KEY (Codigo);
ALTER TABLE EntidadFinancieraC ADD CONSTRAINT pk_EntidadFinancieraC PRIMARY KEY (Codigo);
ALTER TABLE TipoEntidadC ADD CONSTRAINT pk_TipoEntidadC PRIMARY KEY (Codigo);
ALTER TABLE TipoInstitucionC ADD CONSTRAINT pk_TipoInstitucionC PRIMARY KEY (Codigo);
ALTER TABLE AE_SOLICITUDES ADD CONSTRAINT pk_AE_SOLICITUDES PRIMARY KEY (ID_SOLICITUD);
ALTER TABLE Solicitud ADD CONSTRAINT pk_Solicitud PRIMARY KEY (ID_SOLICITUD);
ALTER TABLE PersonaC ADD CONSTRAINT pk_PersonaC PRIMARY KEY (ID);
ALTER TABLE DireccionC ADD CONSTRAINT pk_DireccionC PRIMARY KEY (Codigo);
ALTER TABLE TelefonoC ADD CONSTRAINT pk_TelefonoC PRIMARY KEY (ID);
ALTER TABLE ProteccionDatosC ADD CONSTRAINT pk_ProteccionDatosC PRIMARY KEY (ID, Producto, Codigo);
ALTER TABLE Direccion ADD CONSTRAINT pk_Direccion PRIMARY KEY (Identificador);
ALTER TABLE Pais ADD CONSTRAINT pk_Pais PRIMARY KEY (Codigo);
ALTER TABLE ProteccionDatos ADD CONSTRAINT pk_ProteccionDatos PRIMARY KEY (Identificador);
ALTER TABLE Usuario ADD CONSTRAINT pk_Usuario PRIMARY KEY (ID_SOLICITUD, Identificador);
ALTER TABLE CuestionarioP ADD CONSTRAINT pk_CuestionarioP PRIMARY KEY (Numero);
ALTER TABLE SeccionP ADD CONSTRAINT pk_SeccionP PRIMARY KEY (Identificador);
ALTER TABLE PreguntaP ADD CONSTRAINT pk_PreguntaP PRIMARY KEY (Identificador);
ALTER TABLE Contratante ADD CONSTRAINT pk_Contratante PRIMARY KEY (ID_SOLICITUD);
ALTER TABLE AnexoMat ADD CONSTRAINT pk_AnexoMat PRIMARY KEY (Identificador);
ALTER TABLE AnexoNeo ADD CONSTRAINT pk_AnexoNeo PRIMARY KEY (Identificador);
ALTER TABLE Firma ADD CONSTRAINT pk_Firma PRIMARY KEY (Identificador);
ALTER TABLE ContratoC ADD CONSTRAINT pk_ContratoC PRIMARY KEY (ID);
ALTER TABLE ObservacionesC ADD CONSTRAINT pk_ObservacionesC PRIMARY KEY (Identificador);
ALTER TABLE BeneficiarioC ADD CONSTRAINT pk_BeneficiarioC PRIMARY KEY (ContratoC_ID, ID);
ALTER TABLE AnexoC ADD CONSTRAINT pk_AnexoC PRIMARY KEY (Identificador);
ALTER TABLE PregCuesMedC ADD CONSTRAINT pk_PregCuesMedC PRIMARY KEY (ID, CodPregunta);
ALTER TABLE DirSucursalC ADD CONSTRAINT pk_DirSucursalC PRIMARY KEY (Codigo);
ALTER TABLE FamiliaC ADD CONSTRAINT pk_FamiliaC PRIMARY KEY (ContratoC_ID, ID);
ALTER TABLE UsuarioReg ADD CONSTRAINT pk_UsuarioReg PRIMARY KEY (ID_SOLICITUD, Identificador);
ALTER TABLE Titular ADD CONSTRAINT pk_Titular PRIMARY KEY (ID_SOLICITUD);
ALTER TABLE PreexistenciaC ADD CONSTRAINT pk_PreexistenciaC PRIMARY KEY (ID, Identificador);
ALTER TABLE Preexistencia ADD CONSTRAINT pk_Preexistencia PRIMARY KEY (ID_SOLICITUD, Usuario_Identificador, Identificador);
ALTER TABLE DocumentoG ADD CONSTRAINT pk_DocumentoG PRIMARY KEY (Identificador);
ALTER TABLE ObsEstado ADD CONSTRAINT pk_ObsEstado PRIMARY KEY (Identificador, Id);
ALTER TABLE ErrorWS ADD CONSTRAINT pk_ErrorWS PRIMARY KEY (Identificador);
ALTER TABLE ParentescoDom ADD CONSTRAINT pk_ParentescoDom PRIMARY KEY (Numero, Identificador);
ALTER TABLE MarcaMedicaC ADD CONSTRAINT pk_MarcaMedicaC PRIMARY KEY (ID, Producto, Codigo);
ALTER TABLE TipoSucursalC ADD CONSTRAINT pk_TipoSucursalC PRIMARY KEY (Codigo);
ALTER TABLE ConceptoC ADD CONSTRAINT pk_ConceptoC PRIMARY KEY (IdConcepto);
ALTER TABLE DetalleTarifa ADD CONSTRAINT pk_DetalleTarifa PRIMARY KEY (id_DetalleTarifa);
ALTER TABLE XClass ADD CONSTRAINT pk_XClass PRIMARY KEY (xcodigo);
ALTER TABLE AgentexProducto ADD CONSTRAINT pk_AgentexProducto PRIMARY KEY (Asesor_Id, Id);
ALTER TABLE InstitucionMatNeo ADD CONSTRAINT pk_InstitucionMatNeo PRIMARY KEY (Codigo);
ALTER TABLE LogEstado ADD CONSTRAINT pk_LogEstado PRIMARY KEY (Id);
ALTER TABLE MotDevAreaMedica ADD CONSTRAINT pk_MotDevAreaMedica PRIMARY KEY (Id);
ALTER TABLE ContSinDocSol ADD CONSTRAINT pk_ContSinDocSol PRIMARY KEY (id_ContSinDocSol);
ALTER TABLE LogContSinDocSol ADD CONSTRAINT pk_LogContSinDocSol PRIMARY KEY (id_LogContSinDocSol);
ALTER TABLE LogAsignaciones ADD CONSTRAINT pk_LogAsignaciones PRIMARY KEY (id_LogAsignaciones);
ALTER TABLE ReportesProcAlm ADD CONSTRAINT pk_ReportesProcAlm PRIMARY KEY (id_Reporte);
ALTER TABLE Prorrateo ADD CONSTRAINT pk_Prorrateo PRIMARY KEY (Numero, id_Prorrateo);
ALTER TABLE TipoFactura ADD CONSTRAINT pk_TipoFactura PRIMARY KEY (Codigo);
ALTER TABLE ParamReporte ADD CONSTRAINT pk_ParamReporte PRIMARY KEY (id_ParamReporte);
ALTER TABLE TipoNovedad ADD CONSTRAINT pk_TipoNovedad PRIMARY KEY (Tipo);
ALTER TABLE Novedad ADD CONSTRAINT pk_Novedad PRIMARY KEY (id_Novedad);
ALTER TABLE Causal ADD CONSTRAINT pk_Causal PRIMARY KEY (id_Causal);
ALTER TABLE SolicitudNovedad ADD CONSTRAINT pk_SolicitudNovedad PRIMARY KEY (Id);
ALTER TABLE FamiliaNovedad ADD CONSTRAINT pk_FamiliaNovedad PRIMARY KEY (id_FamiliaNovedad);
ALTER TABLE UsuarioNovedad ADD CONSTRAINT pk_UsuarioNovedad PRIMARY KEY (id_UsuarioNovedad);
ALTER TABLE CausaExclusion ADD CONSTRAINT pk_CausaExclusion PRIMARY KEY (id_CausaExclusion);
ALTER TABLE NovedadCT ADD CONSTRAINT pk_NovedadCT PRIMARY KEY (id_NovedadCT);
ALTER TABLE DocumentoNovedad ADD CONSTRAINT pk_DocumentoNovedad PRIMARY KEY (IdDocumento);
ALTER TABLE NovedadMD ADD CONSTRAINT pk_NovedadMD PRIMARY KEY (id_NovedadMD);
ALTER TABLE LogEstadoSN ADD CONSTRAINT pk_LogEstadoSN PRIMARY KEY (Id);
ALTER TABLE MotivoExcepcionSolNov ADD CONSTRAINT pk_MotivoExcepcionSolNov PRIMARY KEY (Id);
ALTER TABLE PriorizacionSolicitudes ADD CONSTRAINT pk_PriorizacionSolicitudes PRIMARY KEY (EstadoSolicitud, EstadoDoc);
ALTER TABLE LogPriorizacionSol ADD CONSTRAINT pk_LogPriorizacionSol PRIMARY KEY (Id);
ALTER TABLE GrupoAsignacion ADD CONSTRAINT pk_GrupoAsignacion PRIMARY KEY (Id);
ALTER TABLE LogGrupoAsignacion ADD CONSTRAINT pk_LogGrupoAsignacion PRIMARY KEY (Id);
ALTER TABLE LogGruposUsuarios ADD CONSTRAINT pk_LogGruposUsuarios PRIMARY KEY (Id);
ALTER TABLE GrupoAsignacionNovedad ADD CONSTRAINT pk_GrupoAsignacionNovedad PRIMARY KEY (Id);
ALTER TABLE LogFuncionario ADD CONSTRAINT pk_LogFuncionario PRIMARY KEY (Id);
ALTER TABLE LogUsrSolNov ADD CONSTRAINT pk_LogUsrSolNov PRIMARY KEY (Id);
ALTER TABLE ContratoCombo ADD CONSTRAINT pk_ContratoCombo PRIMARY KEY (Id);
ALTER TABLE LogContratoCombo ADD CONSTRAINT pk_LogContratoCombo PRIMARY KEY (Id);
ALTER TABLE ConfiguracionANS ADD CONSTRAINT pk_ConfiguracionANS PRIMARY KEY (Id);
ALTER TABLE LogConfiguracionANS ADD CONSTRAINT pk_LogConfiguracionANS PRIMARY KEY (Id);
ALTER TABLE ConfiguracionFestivos ADD CONSTRAINT pk_ConfiguracionFestivos PRIMARY KEY (Id);
ALTER TABLE LogEstadoDocNov ADD CONSTRAINT pk_LogEstadoDocNov PRIMARY KEY (Id);
ALTER TABLE PlantillaReporte ADD CONSTRAINT pk_PlantillaReporte PRIMARY KEY (id_PlantillaReporte);
ALTER TABLE ReportesDominio ADD CONSTRAINT pk_ReportesDominio PRIMARY KEY (Numero, id_PlantillaReporte);
ALTER TABLE LogInformacionAsesor ADD CONSTRAINT pk_LogInformacionAsesor PRIMARY KEY (id_LogInformacionAsesor);
ALTER TABLE LogHistoricoPlanes ADD CONSTRAINT pk_LogHistoricoPlanes PRIMARY KEY (id_LogHistoricoPlanes);
ALTER TABLE LogLlamadasAE ADD CONSTRAINT pk_LogLlamadasAE PRIMARY KEY (ID);
ALTER TABLE LogLlamadasBH ADD CONSTRAINT pk_LogLlamadasBH PRIMARY KEY (ID);
ALTER TABLE FechaIniEPS ADD CONSTRAINT pk_FechaIniEPS PRIMARY KEY (Id);
ALTER TABLE LogIncompatibilidades ADD CONSTRAINT pk_LogIncompatibilidades PRIMARY KEY (id_LogIncompatibilidades);
ALTER TABLE LogDatosDominio ADD CONSTRAINT pk_LogDatosDominio PRIMARY KEY (id_LogDatosDominio);
ALTER TABLE ContratosExentosFIngreso ADD CONSTRAINT pk_ContratosExentosFIngreso PRIMARY KEY (id_ContratosExentosFIngreso);
ALTER TABLE LogContratosExentosFIngreso ADD CONSTRAINT pk_LogContratosExentosFIngreso PRIMARY KEY (id_LogContratosExentosFIngreso);

ALTER TABLE GridPreferences ADD CONSTRAINT pk_GridPreferences PRIMARY KEY (agentName, piuName);
